### ISSUE TITLE
gmail error: Could not convert socket to TLS

### ISSUE THREAD

**Issue by smarcu** [smarcu/door-sensor#1]
Jun 25, 2016 9:40:37 AM com.teakdata.rpi.doorsensor.MailImpl sendEmail
WARNING: Failed to send message: Could not convert socket to TLS
javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
    javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1999)
    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:709)
    at javax.mail.Service.connect(Service.java:386)
    at javax.mail.Service.connect(Service.java:245)
    at javax.mail.Service.connect(Service.java:194)
    at javax.mail.Transport.send0(Transport.java:253)
    at javax.mail.Transport.send(Transport.java:124)
    at com.teakdata.rpi.doorsensor.MailImpl.sendEmail(MailImpl.java:145)
    at com.teakdata.rpi.doorsensor.MailImpl.access$000(MailImpl.java:38)
    at com.teakdata.rpi.doorsensor.MailImpl$1.call(MailImpl.java:85)
    at com.teakdata.rpi.doorsensor.MailImpl$1.call(MailImpl.java:83)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:543)
    at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:480)
    at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1994)
    ... 14 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.read(InputRecord.java:505)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    ... 20 more

**Comment by smarcu** [comment]
fixed adding 
        properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
